/*
Copyright 2024 DevOps Click.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package config

// mainConfigTemplate is the Go template for the main nginx.conf file.
// It generates the top-level NGINX configuration including worker settings,
// logging, compression, TLS defaults, and monitoring.
const mainConfigTemplate = `# ============================================================================
# NGINX Configuration - Generated by nginx-operator
# DO NOT EDIT - This file is managed by the NGINX Operator
# ============================================================================

worker_processes {{ .WorkerProcesses }};
error_log /var/log/nginx/error.log {{ .ErrorLogLevel }};
pid /var/run/nginx.pid;

{{ if .CustomMainSnippet }}
# --- Custom Main Snippet ---
{{ .CustomMainSnippet }}
{{ end }}

events {
    worker_connections {{ .WorkerConnections }};
    multi_accept on;
    use epoll;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # --- Security ---
    server_tokens {{ .ServerTokens }};

    # --- Logging ---
{{ if .AccessLogFormat }}
    log_format main '{{ .AccessLogFormat }}';
{{ else }}
    log_format main '$remote_addr - $remote_user [$time_local] '
                    '"$request" $status $body_bytes_sent '
                    '"$http_referer" "$http_user_agent" '
                    '$request_time $upstream_response_time';
{{ end }}
{{ if .AccessLogEnabled }}
    access_log /var/log/nginx/access.log main;
{{ else }}
    access_log off;
{{ end }}

    # --- Performance ---
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout {{ .KeepaliveTimeout }};
    keepalive_requests {{ .KeepaliveRequests }};
    client_max_body_size {{ .ClientMaxBodySize }};

    # --- Buffers ---
    client_body_buffer_size 16k;
    client_header_buffer_size 1k;
    large_client_header_buffers 4 8k;

    # --- Timeouts ---
    client_body_timeout 60s;
    client_header_timeout 60s;
    send_timeout 60s;

{{ if .GzipEnabled }}
    # --- Compression ---
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_min_length {{ .GzipMinLength }};
    gzip_types {{ .GzipTypes }};
{{ end }}

{{ if .TLS }}{{ if .TLS.Enabled }}
    # --- TLS Defaults ---
    ssl_protocols {{ join " " .TLS.Protocols }};
{{ if .TLS.Ciphers }}
    ssl_ciphers {{ .TLS.Ciphers }};
{{ end }}
{{ if .TLS.PreferServerCiphers }}
    ssl_prefer_server_ciphers on;
{{ end }}
    ssl_session_cache {{ .TLS.SessionCache }};
    ssl_session_timeout {{ .TLS.SessionTimeout }};
    ssl_session_tickets off;
{{ end }}{{ end }}

{{ if .Monitoring }}{{ if .Monitoring.Enabled }}
    # --- Monitoring ---
    server {
        listen 127.0.0.1:{{ .Monitoring.Port }};
        server_name _;

        location /stub_status {
            stub_status;
            allow 127.0.0.1;
            deny all;
        }

        location /healthz {
            return 200 'ok';
            add_header Content-Type text/plain;
        }
    }
{{ end }}{{ end }}

{{ if .CustomHTTPSnippet }}
    # --- Custom HTTP Snippet ---
    {{ .CustomHTTPSnippet }}
{{ end }}

    # --- Virtual Host Configs ---
    include /etc/nginx/conf.d/*.conf;
}
`

// routeConfigTemplate is the Go template for server block configuration.
// It generates NGINX server {} blocks from NginxRoute specs.
const routeConfigTemplate = `# Route: {{ .ServerName }}
{{ if .RateLimit }}{{ if .RateLimit.Enabled }}
limit_req_zone {{ .RateLimit.Key }} zone={{ .RateLimitZoneName }}:{{ .RateLimit.Zone }} rate={{ .RateLimit.Rate }};
{{ end }}{{ end }}

server {
    listen {{ .ListenPort }}{{ if .ProxyProtocol }} proxy_protocol{{ end }};
{{ if .TLS }}{{ if .TLS.Enabled }}
    listen {{ .HTTPSPort }} ssl{{ if .ProxyProtocol }} proxy_protocol{{ end }};
{{ end }}{{ end }}

    server_name {{ .ServerName }};

{{ if .TLS }}{{ if .TLS.Enabled }}
    # --- TLS ---
{{ if .TLS.SecretName }}
    ssl_certificate /etc/nginx/ssl/{{ .TLS.SecretName }}/tls.crt;
    ssl_certificate_key /etc/nginx/ssl/{{ .TLS.SecretName }}/tls.key;
{{ end }}
{{ end }}{{ end }}

{{ if .TLS }}{{ if .TLS.Enabled }}{{ if .TLS.RedirectHTTP }}
    # --- HTTP to HTTPS Redirect ---
    if ($scheme = http) {
        return 301 https://$host$request_uri;
    }
{{ end }}{{ end }}{{ end }}

{{ if .AccessControl }}
    # --- Access Control ---
{{ range .AccessControl.Allow }}
    allow {{ . }};
{{ end }}
{{ range .AccessControl.Deny }}
    deny {{ . }};
{{ end }}
{{ end }}

{{ if .RateLimit }}{{ if .RateLimit.Enabled }}
    # --- Rate Limiting ---
    limit_req zone={{ .RateLimitZoneName }} burst={{ .RateLimit.Burst }}{{ if .RateLimit.NoDelay }} nodelay{{ end }};
    limit_req_status 429;
{{ end }}{{ end }}

{{ if .Headers }}
    # --- Custom Headers ---
{{ if .Headers.SecurityHeaders }}
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
{{ end }}
{{ range $key, $value := .Headers.Add }}
    add_header {{ $key }} "{{ $value }}" always;
{{ end }}
{{ range .Headers.Remove }}
    proxy_hide_header {{ . }};
{{ end }}
{{ end }}

{{ if .CORS }}{{ if .CORS.Enabled }}
    # --- CORS ---
{{ range .CORS.AllowOrigins }}
    set $cors_origin "{{ . }}";
{{ end }}
    add_header Access-Control-Allow-Origin $cors_origin always;
    add_header Access-Control-Allow-Methods "{{ join ", " .CORS.AllowMethods }}" always;
    add_header Access-Control-Allow-Headers "{{ join ", " .CORS.AllowHeaders }}" always;
{{ if .CORS.AllowCredentials }}
    add_header Access-Control-Allow-Credentials "true" always;
{{ end }}
    add_header Access-Control-Max-Age {{ .CORS.MaxAge }} always;
{{ if .CORS.ExposeHeaders }}
    add_header Access-Control-Expose-Headers "{{ join ", " .CORS.ExposeHeaders }}" always;
{{ end }}
{{ end }}{{ end }}

{{ if .CustomServerSnippet }}
    # --- Custom Server Snippet ---
    {{ .CustomServerSnippet }}
{{ end }}

{{ range .Locations }}
    location {{ .Path }} {
{{ if .UpstreamName }}
        proxy_pass http://{{ .UpstreamName }};
{{ if .ProxySettings }}
        proxy_connect_timeout {{ .ProxySettings.ConnectTimeout }};
        proxy_send_timeout {{ .ProxySettings.SendTimeout }};
        proxy_read_timeout {{ .ProxySettings.ReadTimeout }};
        proxy_buffer_size {{ .ProxySettings.BufferSize }};
        proxy_buffers {{ .ProxySettings.Buffers }};
        proxy_next_upstream {{ .ProxySettings.NextUpstream }};
        proxy_next_upstream_tries {{ .ProxySettings.NextUpstreamTries }};
{{ if .ProxySettings.WebSocket }}
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
{{ end }}
{{ range $key, $value := .ProxySettings.SetHeaders }}
        proxy_set_header {{ $key }} "{{ $value }}";
{{ end }}
{{ else }}
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
{{ end }}
{{ else if .ProxyPass }}
        proxy_pass {{ .ProxyPass }};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
{{ else if .StaticContent }}
        root {{ .StaticContent.Root }};
{{ if .StaticContent.Index }}
        index {{ join " " .StaticContent.Index }};
{{ end }}
{{ if .StaticContent.TryFiles }}
        try_files {{ .StaticContent.TryFiles }};
{{ end }}
{{ if .StaticContent.Autoindex }}
        autoindex on;
{{ end }}
{{ else if .Return }}
        return {{ .Return.Code }}{{ if .Return.Body }} "{{ .Return.Body }}"{{ end }};
{{ end }}

{{ if .RateLimit }}{{ if .RateLimit.Enabled }}
        limit_req zone={{ .RateLimitZoneName }} burst={{ .RateLimit.Burst }}{{ if .RateLimit.NoDelay }} nodelay{{ end }};
{{ end }}{{ end }}

{{ if .Headers }}
{{ range $key, $value := .Headers.Add }}
        add_header {{ $key }} "{{ $value }}" always;
{{ end }}
{{ end }}

{{ if .CustomLocationSnippet }}
        {{ .CustomLocationSnippet }}
{{ end }}
    }
{{ end }}
}
`

// upstreamConfigTemplate is the Go template for upstream block configuration.
// It generates NGINX upstream {} blocks from NginxUpstream specs.
const upstreamConfigTemplate = `# Upstream: {{ .Name }}
upstream {{ .Name }} {
{{ if eq .Algorithm "least_conn" }}
    least_conn;
{{ else if eq .Algorithm "ip_hash" }}
    ip_hash;
{{ else if eq .Algorithm "random" }}
    random{{ if .RandomTwoChoices }} two least_conn{{ end }};
{{ end }}

{{ range .Backends }}
    server {{ .Address }}:{{ .Port }}{{ if ne .Weight 1 }} weight={{ .Weight }}{{ end }}{{ if ne .MaxConnections 0 }} max_conns={{ .MaxConnections }}{{ end }}{{ if ne .MaxFails 3 }} max_fails={{ .MaxFails }}{{ end }}{{ if ne .FailTimeout "10s" }} fail_timeout={{ .FailTimeout }}{{ end }}{{ if .Backup }} backup{{ end }}{{ if .Down }} down{{ end }};
{{ end }}

    keepalive {{ .Keepalive }};
    keepalive_timeout {{ .KeepaliveTimeout }};
    keepalive_requests {{ .KeepaliveRequests }};

{{ if .CustomSnippet }}
    # --- Custom Upstream Snippet ---
    {{ .CustomSnippet }}
{{ end }}
}
`
